src/main/java/com/example/controller/member/MemberController.java, src/main/java/com/example/domain/member/Member.java, src/main/java/com/example/dto/request/ChangeProfileImageRequest.java, src/main/java/com/example/service/community/CommunityService.java, src/main/java/com/example/service/member/MemberService.java
resolve #61
사용자가 자신의 프로필 이미지를 변경할 수 있는 기능을 추가했습니다. 
- `ChangeProfileImageRequest` DTO를 생성하여 프로필 이미지 URL을 받습니다.
- `MemberService`에 `changeProfileImage` 메서드를 추가하여 사용자의 프로필 이미지를 변경합니다.
- `MemberController`에 프로필 이미지 변경 API 엔드포인트를 추가합니다.
=> [feat] 사용자 프로필 이미지 변경 기능 추가 #61

src/main/java/com/example/BuddyApplication.java, src/main/java/com/example/domain/member/Member.java
resolve #63
회원가입 일자를 수집하기 위해 `member` 테이블에 `created_at` 속성을 추가했습니다.
- `member` 테이블에 `created_at` 속성을 추가했습니다.
- Spring Data JPA의 Auditing 기능을 사용하여 회원가입 시 `created_at` 속성에 현재 시간이 자동으로 저장되도록 설정했습니다.
없습니다.
=> [feat]: member 테이블에 created_at 속성 추가 #63

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feat.md, .github/ISSUE_TEMPLATE/fix.md, .github/ISSUE_TEMPLATE/refactor.md
resolve #68 
기존에 사용하던 `github` 템플릿 내 Issue 게시글 생성 시 게시글 `Title` 이슈분류명에
해당하는 단어가 대문자로 구성되어 있었는데, 팀원 간 대소문자 작성에 대한 혼동이 발생하여
해당 문제를 개선하고자 이슈분류명에 해당하는 단어들을 소문자로 일괄적으로 변경하였습니다.
- `bug.md`, `feat.md`, `fix.md`, `help.md`, `refactor.md` 파일 내 `title` 항목의 단어를 소문자로 일괄 변경
- 수정 후 Issue 게시글 생성 시 Title 상태
> `이슈분류명이 소문자로 자동 표시됨.
=> [fix] github 템플릿 내 Issue 게시글 Title lowerCase로 일괄 변경 #68

src/main/java/com/example/controller/subscribe/SubscribeController.java, src/main/java/com/example/exception/ErrorCode.java, src/main/java/com/example/service/subscribe/SubscribeService.java
resolve #71 
사용자는 특정 태그에 대해 구독을 취소한다.
태그 구독 취소하기
[ErrorCode]
존재하지 않는 태그를 구독 취소할 때 :  404
구독하지 않은 태그를 구독 취소할 때 :  404
=> [feat] 태그 구독 취소하기#71

src/main/java/com/example/controller/subscribe/SubscribeController.java, src/main/java/com/example/dto/response/TagSubInfoResponse.java, src/main/java/com/example/exception/ErrorCode.java, src/main/java/com/example/repository/subscribe/TagSubRepository.java, src/main/java/com/example/service/subscribe/SubscribeService.java
resolve #75 
사용자가 자신이 구독한 태그 목록을 조회할 수 있도록 해당 기능을 추가했습니다.
- HTTP 메서드 및 엔드포인트
: GET, /private/subscribe/my-subscribed-tags
- 사용자는 자신의 구독 태그 목록만 조회가 가능합니다.
첫번째 커밋 #78 오타나서 다시 커밋하였습니다.
=> [feat] 회원의 구독 태그 목록 조회 #75

src/main/java/com/example/controller/community/CommentController.java, src/main/java/com/example/domain/community/Comment.java, src/main/java/com/example/dto/request/CommentRequest.java, src/main/java/com/example/exception/ErrorCode.java, src/main/java/com/example/repository/community/CommentRepository.java, src/main/java/com/example/service/community/CommentService.java
resolve #79 
게시글에 대해 사용자가 댓글을 작성, 삭제, 수정할 수 있는 기능을 추가했습니다.
- 댓글 작성 API 추가: POST, /private/posts/{postId}/comment
- 댓글 삭제 API 추가: DELETE, /private/comments/{commentId}
- 댓글 수정 API 추가: PATCH, /private/comments/{commentId}
없습니다.
=> [feat] 댓글 작성/수정/삭제 기능 추가

src/main/java/com/example/domain/community/Post.java, src/main/java/com/example/dto/response/MyPostResponse.java, src/main/java/com/example/repository/community/CommentRepository.java, src/main/java/com/example/repository/community/ReplyRepository.java, src/main/java/com/example/service/community/CommunityService.java
resolve #89
'내가 쓴 커뮤니티 게시글 목록 조회' 기능에 댓글 수를 추가하여 해당 값을 반환 하고자 합니다.
- `MyPostResponse` DTO에 `commentCount` 필드 추가
- `Post` 엔티티와 `Comment` 엔티티 간의 관계를 설정
없습니다
=> [feat] '내가 쓴 커뮤니티 게시글 목록 조회' 기능에 댓글 수 추가 #89

src/main/java/com/example/controller/community/PostLikeController.java, src/main/java/com/example/domain/community/Post.java, src/main/java/com/example/domain/community/PostLike.java, src/main/java/com/example/dto/response/MyPostResponse.java, src/main/java/com/example/exception/ErrorCode.java, src/main/java/com/example/repository/community/CommentRepository.java, src/main/java/com/example/repository/community/PostLikeRepository.java, src/main/java/com/example/repository/community/ReplyRepository.java, src/main/java/com/example/service/community/CommunityService.java, src/main/java/com/example/service/community/PostLikeService.java
resolve #93
'내가 쓴 커뮤니티 게시글 목록 조회' 기능에 likecount를 추가하여 해당 값을 반환하고자 합니다.
- Post 엔티티와  PostLike 엔티티 간의 관계를 설정합니다.
- 게시글 조회 시 좋아요 수를 포함하도록 합니다.
없습니다.
=> [feat] ‘내가 쓴 커뮤니티 게시글 목록 조회’ 기능에 likecount 반환값 추가 #93

src/main/java/com/example/controller/community/CommunityController.java, src/main/java/com/example/controller/party/PartyController.java, src/main/java/com/example/controller/subscribe/SubscribeController.java, src/main/java/com/example/dto/response/TagSubInfoResponse.java, src/main/java/com/example/repository/community/PostRepository.java, src/main/java/com/example/service/subscribe/SubscribeService.java
resolve #95
API 엔드포인트 응답 바디 수정
[엔드포인트]
- 내가 쓴 커뮤니티 게시글 목록 조회 API 엔드포인트 수정
: /private/community/posts/my
- 회원의 구독 태그 목록 조회 API 엔드포인트 수정
: /private/subscribe/my/subscribed-tags
- 나의 파티 목록 조회 API 엔드포인트 수정
: /private/party/my
[응답 바디]
- 회원의 구독 태그 목록 조회 
: API 응답 바디에 postCount(해당 태그가 사용된 모든 게시글 수) 포함
=> [fix] API 엔드포인트 및 응답 바디 수정 #95

src/main/java/com/example/controller/community/CommunityController.java, src/main/java/com/example/controller/subscribe/SubscribeController.java, src/main/java/com/example/dto/response/PostsByTagInfoResponse.java, src/main/java/com/example/dto/response/TagInfoResponse.java, src/main/java/com/example/repository/community/PostRepository.java, src/main/java/com/example/repository/community/PostTagRepository.java, src/main/java/com/example/service/community/CommunityService.java, src/main/java/com/example/service/subscribe/SubscribeService.java
resolve #98
[추천] 태그 등록 수가 가장 높은 상위 10개의 태그 목록 정보를 조회하고자 합니다.
[연관 검색] 검색한 태그와 연관된 태그 목록 정보를 조회하고자 합니다.
- 추천 태그 목록 정보 조회 
: GET /public/community/recommendation-tags
- 연관 검색 태그 목록 정보 조회 
: GET /public/community/search/related-tags?q=지구
- tag 관련 API 엔드포인트/응답 바디 수정
: tag->tags
=> [feat] 추천/연관 검색 태그 목록 정보 조회 기능 추가 #98

build.gradle, src/main/java/com/example/controller/upload/UploadController.java, src/main/java/com/example/repository/community/PostTagRepository.java, src/main/java/com/example/service/upload/UploadService.java, src/main/resources/application.yml
resolve #100
사진 파일을 업로드하고자 한다.
- 파일업로드
:POST, /private/upload
- 다중 업로드 가능
- 총 10MB까지 가능
- 사진 저장 확인용  API Get(/private/upload/image)
- 사진 업로드시 반환된 경로를 해당 API에 입력하면 저장되었는지 확인할 수 있습니다.
=> [feat] 파일 업로드 기능 추가 #100

src/main/java/com/example/controller/community/CommunityController.java, src/main/java/com/example/dto/response/PostsByTagInfoResponse.java, src/main/java/com/example/repository/community/CommentRepository.java, src/main/java/com/example/repository/community/PostRepository.java, src/main/java/com/example/repository/community/PostTagRepository.java, src/main/java/com/example/repository/community/ReplyRepository.java, src/main/java/com/example/service/community/CommunityService.java
resolve #97
태그명(tag)과 조회될 게시글의 최댓값(limit)을 Query String으로 전달하여 게시글 목록 정보를 조회한다.
- 태그 기반 커뮤니티 게시글 목록 정보 조회
: GET /public/community/posts?tag=애니메이션&limit=5)
추후 추가 필요한 항목
- 수정시간(modifyAt)
- 댓글 및 답글 좋아요 (comment/replyLikeCount)
=> [feat] 태그 기반 커뮤니티 게시글 목록 정보 조회 기능 추가 #97

src/main/java/com/example/controller/community/CommunityController.java, src/main/java/com/example/dto/response/CommunityPostResponse.java, src/main/java/com/example/service/community/CommunityService.java
resolve #104
커뮤니티 게시글에 대한 정보를 조회할 수 있는 API를 구현했습니다. 
- 커뮤니티 게시글 조회 API 구현: GET /public/community/posts/{postId}
- DTO 추가: CommunityPostResponse 클래스 추가 
- 컨트롤러 및 서비스 구현: CommunityController 및 CommunityService에 API 로직 추가
=> [feat] 커뮤니티 게시글 정보 조회 API 추가 #104

src/main/java/com/example/controller/community/CommunityController.java, src/main/java/com/example/dto/response/CommunityPostResponse.java, src/main/java/com/example/service/community/CommunityService.java
resolve #106
최신 커뮤니티 게시글 목록을 조회할 수 있는 API를 추가하였습니다.
- 최신 커뮤니티 게시글 목록 조회 API 구현: GET /public/community/posts/latest?limit={limit}
- 컨트롤러 및 서비스 구현: CommunityController와 CommunityService에 최신 게시글 조회 로직 추가
기존에 /public/community/posts 경로가 태그 기반 게시글 조회 API와 중복될 수 있어, 최신 게시글 조회를 위한 경로를 /public/community/posts/latest로 변경하였습니다.
=> [feat] 최신 커뮤니티 게시글 목록 조회 API 추가 #106

src/main/java/com/example/controller/community/CommentController.java, src/main/java/com/example/domain/community/CommentLike.java, src/main/java/com/example/domain/community/CommentLikeId.java, src/main/java/com/example/exception/ErrorCode.java, src/main/java/com/example/repository/community/CommentLikeRepository.java, src/main/java/com/example/service/community/CommentService.java
resolve #109 
댓글에 좋아요 및 좋아요 취소 기능을 추가했습니다.
- 댓글 좋아요 기능 추가: POST, /private/posts/comments/{commentId}/like API를 통해 사용자가 댓글에 좋아요를 누를 수 있도록 구현.
- 댓글 좋아요 취소 기능 추가: DELETE, /private/posts/comments/{commentId}/like API를 통해 사용자가 댓글에 이미 누른 좋아요를 취소할 수 있도록 구현.
없습니다.
=> [feat] 댓글 좋아요/취소 API 추가 #109

src/main/java/com/example/controller/community/ReplyController.java, src/main/java/com/example/domain/community/ReplyLike.java, src/main/java/com/example/domain/community/ReplyLikeId.java, src/main/java/com/example/exception/ErrorCode.java, src/main/java/com/example/repository/community/ReplyLikeRepository.java, src/main/java/com/example/service/community/ReplyService.java
resolve #111
답글에 좋아요 및 좋아요 취소 기능을 추가하였습니다. 
- 답글 좋아요 API 추가: POST,  /private/comments/replies/{replyId}/like 경로를 통해 특정 답글에 좋아요를 누를 수 있도록 구현하였습니다.
- 답글 좋아요 취소 API 추가: DELETE, /private/comments/replies/{replyId}/like 경로를 통해 특정 답글에 대한 좋아요를 취소할 수 있도록 구현하였습니다.
없습니다.
=> [feat] 답글 좋아요/취소 API 추가 #109-111

src/main/java/com/example/controller/community/PostLikeController.java, src/main/java/com/example/domain/community/ReplyLike.java, src/main/java/com/example/exception/ErrorCode.java, src/main/java/com/example/service/community/PostLikeService.java, src/main/java/com/example/service/community/ReplyService.java
resolve #114 
#111 작업을 통해 추가되었던 `답글 좋아요 취소하기` API에서 DB에 존재하지 않는
데이터에 대하여 요청을 시도할 경우 400 에러가 발생하였는데, 이를 404 에러로
반환되도록 관련 코드를 수정하고자 하였습니다. 추가적으로, `게시글 좋아요 취소하기` API의
경우도 위와 같은 맥락에서 관련 코드를 수정하였습니다.
- 기존 `post_like` 테이블명을 복수 명사로 변경(`post_likes`)
- `게시글 좋아요 취소하기` API의 400 에러를 404 에러로 반환되도록 수정
- `답글 좋아요 취소하기` API의 400 에러를 404 에러로 반환되도록 수정
없습니다
=> [fix] 기존 {post_like} 테이블명의 복수형으로 수정 및 {좋아요 취소하기} API 관련 400 에러 반환 코드의 404 에러가 반환되도록 수정 #114

src/main/java/com/example/controller/community/CommunityController.java, src/main/java/com/example/domain/community/Post.java, src/main/java/com/example/dto/response/MyPostResponse.java, src/main/java/com/example/dto/response/PostsByTagInfoResponse.java, src/main/java/com/example/dto/response/SearchResponse.java, src/main/java/com/example/dto/response/SearchTagsResponse.java, src/main/java/com/example/exception/ErrorCode.java, src/main/java/com/example/repository/community/CommentLikeRepository.java, src/main/java/com/example/repository/community/PostRepository.java, src/main/java/com/example/repository/community/PostTagRepository.java, src/main/java/com/example/repository/community/ReplyLikeRepository.java, src/main/java/com/example/service/community/CommunityService.java
resolve #108
게시글 검색 정보 조회, 태그 관련 통합 검색 정보를 조회하고자 합니다.
- **API:** `GET /public/community/search/posts?q=도라에몽&limit=10`
- **설명:** 
- 검색된 `query` 값과 관련된 연관 커뮤니티 태그 목록 정보와 (게시글 제목, 내용, 게시글 내 등록된 태그, 작성자명) 중 하나라도 일치하는 게시글에 대한 정보를 반환합니다.
- `limit` 파라미터는 날짜가 최신인 게시글들의 조회 개수를 제한하는 역할을 하며, 조정이 가능합니다.
- **예외 상황:** 관련된 정보가 하나도 존재하지 않는 경우 `404` 에러를 반환합니다.
- **API:** `GET /public/community/search/tags?q=도라에몽&limit=10`
- **설명:** 
- 검색된 `query` 값과 일치하는 커뮤니티 태그 및 연관 커뮤니티 태그 목록 정보와 (게시글 제목, 내용, 게시글 내 등록된 태그, 작성자명) 중 하나라도 일치하는 게시글에 대한 정보를 반환합니다.
- `relatedSearchTag` 객체에는 검색된 태그를 제외한 나머지 연관 커뮤니티 태그 목록 정보가 포함되어야 합니다.
- `limit` 파라미터는 최신 게시글들의 조회 개수를 제한하며, 조정이 가능합니다.
- **예외 상황:** DB에 `도라에몽`에 대한 태그 데이터가 존재하지 않는 경우, 클라이언트가 해당 API를 호출할 때 (`GET /public/community/search/tags?q=도라에몽&limit=10`) `tagId`, `tag`, …
=> [feat] 게시글 검색 정보 조회 / 태그 관련 통합 검색 정보 조회기능 추가 #113-108

src/main/java/com/example/controller/community/CommunityController.java, src/main/java/com/example/repository/community/PostRepository.java, src/main/java/com/example/service/community/CommunityService.java
resolve #118
인기 커뮤니티 게시글 목록 정보를 조회합니다.
커뮤니티 게시글 정보 조회 API에 조회수 증가 로직을 추가합니다.
- 인기 커뮤니티 게시글 목록 정보 조회
- GET, /public/community/posts/hot)
- 커뮤니티 내 전체 게시글 중에서 게시글의 조회수(views)가 가장 높은 상위 5개의 게시글 정보를 조회한다.
- 커뮤니티 게시글 정보 조회
-  API 사용 시 해당 게시글에 해당하는 views + 1으로 증가시킨다.
게시글의 조회수가 같을 경우 최근 작성된 게시글을 우선으로 반환합니다.
=> [feat] 인기 커뮤니티 게시글 목록 정보 조회 기능 추가 / 조회수 증가 로직 추가

src/main/java/com/example/BuddyApplication.java, src/main/java/com/example/config/async/AsyncConfig.java, src/main/java/com/example/service/email/EmailService.java
resolve #112
파티의 마지막 멤버가 파티에 가입할 때, 해당 파티의 모든 파티원에게 파티 매칭 완료 이메일 전송을 함으로 인해 파티 가입 완료 알림이 지연됩니다.
- 이메일 발송 메서드(sendEmail)에 @Async 적용하여 비동기 처리 구현
=> [fix] 파티 매칭 완료시 이메일 전송 서비스 로직 수정 및 기능 개선 #122

src/main/java/com/example/service/party/PartyService.java
resolve #126
특정 플랜 내 매칭이 완료되지 않은 파티 목록 정보 조회 API 응답 에러 수정
특정 플랜 내 매칭이 완료되지 않은 파티 목록 정보 조회 API에서 현재 파티의 시작일자(startDate)가 오늘보다 이전인 파티는 응답 바디를 포함하지 않도록 로직을 추가했습니다.
=> [bug] 특정 플랜 내 매칭이 완료되지 않은 파티 목록 정보 조회 API 응답 에러 #126

src/main/java/com/example/controller/party/PartyController.java, src/main/java/com/example/repository/party/PartyRepository.java, src/main/java/com/example/service/party/PartyService.java
resolve #130 
현재 매칭 대기 중인 모든 파티의 파티원 총 인원수 합산 값 조회 API 응답 에러 수정
현재 매칭 대기 중인 모든 파티의 파티원 총 인원수 합산 값 조회 API에서 현재 파티의 시작일자(startDate)가 오늘보다 이전인 파티원의 수도 합산에 포함됩니다. 해당 파티를 포함하지 않도록 로직을 추가했습니다.
=> [bug] 현재 매칭 대기 중인 모든 파티의 파티원 총 인원수 합산 값 조회 API 응답 에러 #130
